schema_version = "1.0.0"

id = "milky_edge_flow_tools"
version = "0.8.0" # x-release-please-version
name = "milkyEdgeFlowTools"
tagline = "Relax crossing edge flows by resampling selected edge loops"
maintainer = "takagiy <takagiy.4dev@gmail.com>"
type = "add-on"

blender_version_min = "5.0.0"

license = ["SPDX:GPL-3.0-or-later"]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  ".*",
  "/dist/",
  "/test_*.py",
  "/pyproject.toml",
  "/uv.lock",
  "/requirements.md",
  "/README.md",
  "/README_ja.md",
  "/CHANGELOG.md",
  "/version.txt",
  "/release-please-config.json",
  "/tools/",
]
